### PR TITLE
Try to load all specs, matching to the current *features*.

### PR DESCRIPTION
**Pull request by svetlyak40wt**
This should fix a problem of having libraries for different architectures
on Apple M1.

### CODE REVIEW

**Comment by svetlyak40wt** [comment]
@sionescu please, review this pull?

**Comment by sionescu** [comment]
As it is, this is not going in.

**Comment by svetlyak40wt** [comment]
Why not?

**Comment by svetlyak40wt** [comment]
@sionescu what was wrong with this pull. What should be fixed?

**Comment by luismbo** [comment]
@svetlyak40wt `define-foreign-library` was designed and is documented to work like a `cond` and existing code depends on that. (e.g., they may have specific declarations for openbsd and a generic one for other unix systems).

Perhaps you'd like to start a [discussion](https://github.com/cffi/cffi/discussions) about the Apple M1 issue you're having and what CFFI can do to help, if anything.

**Pull request closed without merging**
