### PR TITLE
Solaris ld doesn't do --export-dynamic

### PR DESCRIPTION
**Pull request by jesseoff**
I believe all symbols are default exported w/the Solaris linker

### CODE REVIEW

**Comment by luismbo** [comment]
Which Lisps use `:sunos` and which use the `:solaris` feature?

**Comment by jesseoff** [comment]
I only have two successfully running on my Solaris machine.  sbcl uses :sunos and ccl uses :solaris

**Comment by priyadarshan** [comment]
> 
> 
> Which Lisps use `:sunos` and which use the `:solaris` feature?

If I may butt in, on [LispWorks](http://www.lispworks.com/documentation/lw70/LW/html/lw-373.htm) is `:solaris2`

**Comment by luismbo** [comment]
@jesseoff could you add this to trivial-features so that we can use `:solaris` everywhere?

**Comment by jesseoff** [comment]
Will do.  Maybe I'll try to see if ecl also can build and what it uses.

**Comment by jesseoff** [comment]
I have a pending pull request in trivial-features to normalize :sunos in *features* (the default for sbcl)  If that gets approved, I'll update this to use only :sunos

**Pull request merged**
