### PR TITLE
commented out the style warning as it seriously degrades the performa…

### PR DESCRIPTION
**Pull request by jimka2001**
I'm creating this PR to suggest a change in CFFI.
I was having serious performance problems in an application I'm working on, but didn't implement.
The application uses cl-gtk2-gtk.
The problem I was having was that my mouse events were producing so much output into the REPL that it was unusable, and it looked like some events were getting lost.  I'm not 100% sure anything was actually getting lost but because of the volumes of repeated style warnings, the system was unusable.

I commented out this style warning, and it make the program much more responsive.

It is not clear to me why I get the style warning 1000s of times.  It could be that my program is doing some sort of run-time compilation or evaluation.  As I said I didn't write the program, just starting working on it.

### CODE REVIEW

**Comment by luismbo** [comment]
I think this should be fixed on the cl-gtk2-gtk side. Have you considered that alternative?

**Comment by jimka2001** [comment]
Fixed how in cl-gtk2-gtk?

**Comment by jimka2001** [comment]
Does anyone know what these style warnings are trying to tell me.  What is it asking me to do?
Is it asking me to modify the defcstruct or defcunion call-site?  If that's the case, it is not necessary as it has already fixed itself in its macro expansion.  Or is it asking me to change the places in the code where this particular cstruct/cunion is being referenced in the code?

**Comment by guicho271828** [comment]
@jimka2001 you should see the source code of the structure type mentioned in the warning. Tell us what it is and search https://github.com/dmitryvk/cl-gtk2 for its definition, and maybe make a pull request. (but hey, the development seems inactive...)

**Comment by jimka2001** [comment]
HI Masataro, one problem with the cffi style warning is that it does not
give the user any clue about where the issue occurred.
I.e., it doesn't tell me which piece of code triggered the style warning.
During my investigation, I modified the warning to give better
information.  In doing so I added an extra argument to
parse-deprecated-struct-type
definition and all the call-sites I could find.

I didn't push those changes to the github branch as I found it was better
simply to comment out the call to simple-style-warning.
Nevertheless, while discussing this issue, it might be good for me to
re-instante that temporary change to to show what happens.

**Comment by jimka2001** [comment]
Here is an example of the style warnings emitted by this new version of the code (e395814).
In fact every time I move the mouse in the gtk canvas, I get 100s of these messages printed into the REPL.

STYLE-WARNING:
   bare references to struct types are deprecated. Please use (:POINTER
                                                               (:STRUCT
                                                                GDK::EVENT-MOTION-CSTRUCT)) or (:STRUCT
                                                                                                GDK::EVENT-MOTION-CSTRUCT) instead of EVENT-MOTION-CSTRUCT STRUCT 
in (DEFCSTRUCT EVENT-MOTION-CSTRUCT
     (TYPE EVENT-TYPE)
     (WINDOW (G-OBJECT GDK-WINDOW))
     (SEND-EVENT (BOOLEAN INT8))
     (TIME UINT32)
     (X DOUBLE)
     (Y DOUBLE)
     (AXES (FIXED-ARRAY DOUBLE 2))
     (STATE MODIFIER-TYPE)
     (IS-HINT INT16)
     (DEVICE (G-OBJECT GDK-DEVICE))
     (X-ROOT DOUBLE)
     (Y-ROOT DOUBLE)).

**Comment by luismbo** [comment]
@jimka2001 it's a nice idea to show where the warning comes from. I would prefer not to disable the warnings, though, since the idea is to remove the old style of structure types at some point the in future. Can you clean your patch up taking this into account? Thanks!

**Comment by jimka2001** [comment]
Hi Luismbo, did you understand my point that my gtk application is unusable with these warnings enabled?  The warnings seem to cause a significant performance penalty.  I don't understand why they are issued at runtime.  Neither do I understand why they are issued (in the since of what mechanism is triggering them), nor why they are issued (in the since of why the author of the code wants to issue them.

To me the style warning does not tell me what I need to change in my code.

Can you please help me understand the warning.  
Does it want me to change the 
(DEFCSTRUCT EVENT-MOTION-CSTRUCT ...)
to
(DEFCSTRUCT (:struct EVENT-MOTION-CSTRUCT ...))

Is it telling me to change the definition site or the call site?

**Comment by luismbo** [comment]
@jimka2001 oh, heh, I got confused by your change to the warning. :-) The warnings come from call sites (i.e. places that use the `event-motion-cstruct`). Change the warning to a call to `break` and that'll show you where the call site is, hopefully.

**Comment by jimka2001** [comment]
OK, I put a break in the function as you suggest.  It looks like the gtk call (or at least the first such one) comes from here.

(defun g-value-zero (g-value)
  "Initializes the GValue in \"unset\" state.

@arg[g-value]{a C pointer to the GValue structure}"
  (loop
     for i from 0 below (foreign-type-size 'g-value)
     do (setf (mem-ref g-value :uchar i) 0)))

Even if I replace g-value with (:pointer g-value), I still get the warning and a break with the same stack trace.

Here is the stack trace I get:

Backtrace:
  0: (CFFI::PARSE-DEPRECATED-STRUCT-TYPE GOBJECT.FFI:G-VALUE #<unavailable argument> (CFFI:DEFCSTRUCT GOBJECT.FFI:G-VALUE (:TYPE GOBJECT.FFI:G-TYPE-DESIGNATOR) (:DATA GOBJECT.FFI:G-VALUE-DATA :COUNT 2)))
  1: (CFFI::PARSE-TYPE GOBJECT.FFI:G-VALUE)
  2: ((LAMBDA (&OPTIONAL TYPE) :IN "/Users/jnewton/sw/cffi/src/early-types.lisp") GOBJECT.FFI:G-VALUE)
  3: (CFFI::PARSE-TYPE GOBJECT.FFI:G-VALUE)
  4: ((:METHOD CFFI:FOREIGN-TYPE-SIZE (T)) GOBJECT.FFI:G-VALUE) [fast-method]
  5: (GOBJECT:G-VALUE-ZERO #.(SB-SYS:INT-SAP #X0050C438))
  6: (GOBJECT:SET-G-VALUE #.(SB-SYS:INT-SAP #X0050C438) "Climb" #<unavailable argument> :ZERO-G-VALUE T :UNSET-G-VALUE NIL :G-VALUE-INIT T)
  7: (GOBJECT:G-OBJECT-CALL-CONSTRUCTOR "GtkWindow" ("default-height" "default-width" "title" "window-position" "type") (480 640 "Climb" :CENTER :TOPLEVEL) (NIL NIL NIL NIL NIL))
  8: (GOBJECT::CREATE-GOBJECT-FROM-CLASS-AND-INITARGS #<GOBJECT:GOBJECT-CLASS GTK:GTK-WINDOW> (:TYPE :TOPLEVEL :WINDOW-POSITION :CENTER :TITLE "Climb" ...))
  9: ((:METHOD MAKE-INSTANCE (GOBJECT:GOBJECT-CLASS)) #<GOBJECT:GOBJECT-CLASS GTK:GTK-WINDOW> :TYPE :TOPLEVEL :WINDOW-POSITION :CENTER :TITLE "Climb" :DEFAULT-WIDTH 640 :DEFAULT-HEIGHT 480) [fast-method]
 10: ((LAMBDA NIL :IN FR.EPITA.LRDE.CLIMB-GUI:RUN))
 11: ((LAMBDA (GTK::DATA) :IN "/Users/jnewton/sw/cl-gtk2/gtk/gtk.misc.lisp") #.(SB-SYS:INT-SAP #X00000002))
 12: ((LAMBDA (SB-ALIEN::ARGS-POINTER SB-ALIEN::RESULT-POINTER FUNCTION) :IN "/Users/jnewton/.cache/common-lisp/sbcl-1.2.12.61-9741c60-macosx-x64/Users/jnewton/sw/cl-gtk2/glib/gobject.object.high.fasl") 55..
 13: ("foreign function: call_into_lisp")

**Comment by luismbo** [comment]
The stacktrace suggests that somehow your change didn't take effect as `foreign-type-size` was passed `'g-value` (frame 4). In that context, the change should be to '(:struct g-value) btw.

**Comment by guicho271828** [comment]
Maybe you like this recent post in reddit? :) https://www.reddit.com/r/lisp/comments/3cinpv/debugging_lisp_part_1_recompilation/

**Comment by jimka2001** [comment]
Hi Luismbo,

I think the actual style warning depends on how I move the mouse.

Here is the latest stack trace after inserting the break.  The call site is not obvious to me as the code does not seem to explicitly reference event-motion-cstruct, as far as i can see.  BTW, I'm effectively trying to debug cl-gtk, which I didn't write and don't understand.


bare references to struct types are deprecated. Please use (:POINTER
                                                            #1=(:STRUCT
                                                                GDK::EVENT-MOTION-CSTRUCT)) or #1# instead of EVENT-MOTION-CSTRUCT STRUCT 
in (DEFCSTRUCT EVENT-MOTION-CSTRUCT
     (TYPE EVENT-TYPE)
     (WINDOW (G-OBJECT GDK-WINDOW))
     (SEND-EVENT (BOOLEAN INT8))
     (TIME UINT32)
     (X DOUBLE)
     (Y DOUBLE)
     (AXES (FIXED-ARRAY DOUBLE 2))
     (STATE MODIFIER-TYPE)
     (IS-HINT INT16)
     (DEVICE (G-OBJECT GDK-DEVICE))
     (X-ROOT DOUBLE)
     (Y-ROOT DOUBLE)).
   [Condition of type SIMPLE-CONDITION]

Restarts:
 0: [CONTINUE] Return from BREAK.
 1: [ABORT] abort thread (#<THREAD "cl-gtk2 main thread" RUNNING {124B6D4EE3}>)

Backtrace:
  0: (CFFI::PARSE-DEPRECATED-STRUCT-TYPE GDK::EVENT-MOTION-CSTRUCT #<unavailable argument> (CFFI:DEFCSTRUCT GDK::EVENT-MOTION-CSTRUCT (TYPE GDK:EVENT-TYPE) (GDK::WINDOW (GOBJECT:G-OBJECT GDK:GDK-WINDOW)) (..
  1: (CFFI::PARSE-TYPE GDK::EVENT-MOTION-CSTRUCT)
  2: (CFFI::GET-SLOT-INFO GDK::EVENT-MOTION-CSTRUCT TYPE)
  3: (CFFI:FOREIGN-SLOT-VALUE #.(SB-SYS:INT-SAP #X0108C090) GDK::EVENT-MOTION-CSTRUCT TYPE)
  4: (GOBJECT::COPY-SLOTS-TO-PROXY #S(GDK:EVENT-MOTION :TYPE :MOTION-NOTIFY :WINDOW NIL :SEND-EVENT NIL :TIME NIL :X NIL :Y NIL ...) #.(SB-SYS:INT-SAP #X0108C090) #S(GOBJECT::CSTRUCT-DESCRIPTION :NAME GDK:..
      Locals:
        SB-DEBUG::ARG-0 = #S(GDK:EVENT-MOTION :TYPE :MOTION-NOTIFY :WINDOW NIL :SEND-EVENT NIL :TIME NIL :X NIL :Y NIL ...)
        SB-DEBUG::ARG-1 = #.(SB-SYS:INT-SAP #X0108C090)
        SB-DEBUG::ARG-2 = #S(GOBJECT::CSTRUCT-DESCRIPTION ..)
  5: ((:METHOD CFFI:TRANSLATE-FROM-FOREIGN (T GOBJECT::BOXED-VARIANT-CSTRUCT-FOREIGN-TYPE)) #.(SB-SYS:INT-SAP #X0108C090) #<GOBJECT::BOXED-VARIANT-CSTRUCT-FOREIGN-TYPE {124EDE12A3}>) [fast-method]
      Locals:
        SB-DEBUG::ARG-2 = #.(SB-SYS:INT-SAP #X0108C090)
        SB-DEBUG::ARG-3 = #<GOBJECT::BOXED-VARIANT-CSTRUCT-FOREIGN-TYPE {124EDE12A3}>
  6: (GOBJECT::PARSE-CLOSURE-ARGUMENTS 2 #.(SB-SYS:INT-SAP #X08A6D210))
      Locals:
        SB-DEBUG::ARG-0 = 2
        SB-DEBUG::ARG-1 = #.(SB-SYS:INT-SAP #X08A6D210)
  7: ((LAMBDA (GOBJECT::CLOSURE GOBJECT::RETURN-VALUE GOBJECT::COUNT-OF-ARGS GOBJECT::ARGS GOBJECT::INVOCATION-HINT GOBJECT::MARSHAL-DATA) :IN "/Users/jnewton/sw/cl-gtk2/glib/gobject.signals.lisp") #.(SB-S..
      Locals:
        SB-DEBUG::ARG-0 = #.(SB-SYS:INT-SAP #X0A126380)
        SB-DEBUG::ARG-1 = #.(SB-SYS:INT-SAP #X08A6D168)
        SB-DEBUG::ARG-2 = 2
        SB-DEBUG::ARG-3 = #.(SB-SYS:INT-SAP #X08A6D210)
  8: ((LAMBDA (SB-ALIEN::ARGS-POINTER SB-ALIEN::RESULT-POINTER FUNCTION) :IN "/Users/jnewton/.cache/common-lisp/sbcl-1.2.12.61-9741c60-macosx-x64/Users/jnewton/sw/cl-gtk2/glib/gobject.signals.fasl") 725750..
      Locals:
        SB-DEBUG::ARG-0 = 72575004
        SB-DEBUG::ARG-1 = 72575000
        SB-DEBUG::ARG-2 = #<FUNCTION (LAMBDA (GOBJECT::CLOSURE GOBJECT::RETURN-VALUE GOBJECT::COUNT-OF-ARGS GOBJECT::ARGS GOBJECT::INVOCATION-HINT GOBJECT::MARSHAL-DATA) ..) {106509CE1B}>
  9: ("foreign function: call_into_lisp")
 10: ("foreign function: funcall3")
 11: ("foreign function: callback_wrapper_trampoline")
 12: ("foreign function: #x20100EAB")
 13: ("foreign function: #xFFFFFFFFFFFFFFFF")
 14: ("foreign function: signal_emit_unlocked_R")
 15: ("foreign function: g_signal_emit_valist")
 16: ("foreign function: g_signal_emit")
 17: ("foreign function: gtk_widget_event_internal")
 18: ("foreign function: gtk_propagate_event")
 19: ("foreign function: gtk_main_do_event")
 20: ("foreign function: gdk_event_dispatch")
 21: ("foreign function: g_main_context_dispatch")
 22: ("foreign function: g_main_context_iterate")
 23: ("foreign function: g_main_loop_run")
 24: ("foreign function: gtk_main")
 25: (GTK::%GTK-MAIN)
 26: (GTK:GTK-MAIN)
 27: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))

**Comment by luismbo** [comment]
It makes sense that moving the mouse in different ways triggers different events, which in turn trigger different code paths. If you don't have the time/inclination to fix this in cl-gtk2, I think you should report it as a bug, and disable the warning as a workaround in your code. HTH.

**Comment by luismbo** [comment]
But, of course, if you do feel like fixing this issue in cl-gtk2, I'll be glad to help you out. :)

**Comment by jimka2001** [comment]
Actually I'd be very happy to fix this if you can show me how.  I do have some time indeed to work on it.

**Comment by luismbo** [comment]
I should have said "I would be glad to help you with CFFI-specific issues". I don't have time atm to understand how cl-gtk2 works. If I had time, I'd start by trying to figure out where COPY-SLOTS-TO-PROXY is getting the struct type from.

**Comment by jimka2001** [comment]
Hi Luís,
It looks to me like the function  g-value-zero is suspicious.  It is trying to find the size of the g-value object, (foreign-type-size 'g-value),  in order to zero it out.  

https://github.com/dmitryvk/cl-gtk2/blob/master/glib/gobject.gvalue.lisp#L3-L9

This is called from 

https://github.com/dmitryvk/cl-gtk2/blob/master/glib/gobject.gvalue.lisp#L82-L114

Here is the code for foreign-type-size
https://github.com/cffi/cffi/blob/master/src/early-types.lisp#L119-L121

It apparently calls parse-type on its argument, which is the symbol g-type.

Is this the deprecated action?    With the newest cffi, what is the correct way to find the size of g-object, in a non-deprecated way?

**Comment by jimka2001** [comment]
https://github.com/dmitryvk/cl-gtk2/blob/master/glib/gobject.gvalue.lisp#L3-L9

**Comment by luismbo** [comment]
`(foreign-type-size '(:struct g-value))`

**Comment by jimka2001** [comment]
I've made a change in cl-gtk2 which seems to greatly improve the situation.  At least it seems eliminates the run-time style warnings, but not the compile time ones. https://github.com/dmitryvk/cl-gtk2/pull/13

**Pull request closed without merging**
