### PR TITLE
Bitfield groveller accepts defctyped-type

### PR DESCRIPTION
**Pull request by guicho271828**
https://bugs.launchpad.net/cffi/+bug/1505321

### CODE REVIEW

**Comment by sionescu** [comment]
Thanks, I merged with a small modification

**Comment by guicho271828** [comment]
I now noticed an invention of a wheel. canonicalize-foreign-type should do the job. Is that the modification?

**Comment by sionescu** [comment]
Yes :)

**Comment by guicho271828** [comment]
:+1:

**Pull request closed without merging**
