### PR TITLE
Adds link to launchpad for bug reporting

### PR DESCRIPTION
**Pull request by vydd**

### CODE REVIEW

**Comment by guicho271828** [comment]
ping @attila-lendvai

**Comment by attila-lendvai** [comment]
it's not my responsibility to decide. and if it were, i would go with the github issue tracker.

@luismbo may have something to add here.

**Comment by vydd** [comment]
To give some context now that 9 months have passed, I did this because someone on #lisp told me that  all bugs should go to launchpad, so I thought that that info should be available in the README as well.

**Comment by fiddlerwoaroof** [comment]
There is no issue tracker on the github repository and no link to Launchpad, which makes it hard to see what issues have been reported.  Can we merge this commit in?

**Comment by luismbo** [comment]
Fixed via c28c760. I guess we need to replicate the website info in the README.md since that's probably got much more visibility these days.

**Pull request closed without merging**
