### PR TITLE
ADDED: Support for Lisp implementation CLASP.

### PR DESCRIPTION
**Pull request by dg1sbg**
This should be it... Thx again!

### CODE REVIEW

**Comment by luismbo** [comment]
Not sure how CLASP handles unicode encoded source files but I'm slightly nervous about that. It's 2017, I know, but I'm still bitten by things like that pretty often. I have a couple of minor suggestions. What do you think?

```diff
diff --git a/src/cffi-clasp.lisp b/src/cffi-clasp.lisp
index fe3e8e9..d699283 100644
--- a/src/cffi-clasp.lisp
+++ b/src/cffi-clasp.lisp
@@ -1,8 +1,8 @@
 ;;;; -*- Mode: lisp; indent-tabs-mode: nil -*-
 ;;;
-;;; cffi-clasp.lisp --- CLASP backend for CFFI.
+;;; cffi-clasp.lisp --- CFFI-SYS implementation for CLASP.
 ;;;
-;;; by Frank Gönninger, <frank.goenninger@goenninger.net>
+;;; Copyright (C) 2017 Frank Goenninger  <frank.goenninger@goenninger.net>
 ;;;
 ;;; Permission is hereby granted, free of charge, to any person
 ;;; obtaining a copy of this software and associated documentation
@@ -25,8 +25,6 @@
 ;;; DEALINGS IN THE SOFTWARE.
 ;;;
 
-
-
 ;;;# Administrivia
 
 (defpackage #:cffi-sys
@@ -99,7 +97,7 @@ SIZE-VAR is supplied, it will be bound to SIZE during BODY."
 (deftype foreign-pointer ()
   'clasp-ffi:foreign-data)
 
-(defun null-pointer-p ( ptr )
+(defun null-pointer-p (ptr)
   "Test if PTR is a null pointer."
   (clasp-ffi:%null-pointer-p ptr))
 
@@ -125,9 +123,8 @@ SIZE-VAR is supplied, it will be bound to SIZE during BODY."
 
 (defun pointer-eq (ptr1 ptr2)
   "Return true if PTR1 and PTR2 point to the same address."
-  (when (or (not (pointerp ptr1))
-            (not (pointerp ptr2)))
-    (error "POINTER-EQ: An argument is not of type ~S: Arg1 ~S (~S), Arg2 ~S (~S)" 'foreign-pointer ptr1 (type-of ptr1) ptr2 (type-of ptr2)))
+  (check-type ptr1 clasp-ffi:foreign-data)
+  (check-type ptr2 clasp-ffi:foreign-data)
   (eql (pointer-address ptr1) (pointer-address ptr2)))
 
 
@@ -160,7 +157,6 @@ WITH-POINTER-TO-VECTOR-DATA."
 
 (defun %mem-ref (ptr type &optional (offset 0))
   "Dereference an object of TYPE at OFFSET bytes from PTR."
-  #+clasp-ffi.debug (format *debug-io* "~&%mem-ref: ptr = ~S, type = ~S, offset = ~S.~&" ptr type offset)
   (clasp-ffi:%mem-ref ptr type offset))
 
 (defun %mem-set (value ptr type &optional (offset 0))
@@ -189,7 +185,6 @@ WITH-POINTER-TO-VECTOR-DATA."
 
 (defun %foreign-symbol-pointer (name library)
   "Returns a pointer to a foreign symbol NAME."
-  (declare (ignorable library))
   (clasp-ffi:%foreign-symbol-pointer name library))
 
 (defun native-namestring (pathname)
@@ -199,11 +194,8 @@ WITH-POINTER-TO-VECTOR-DATA."
 
 (defmacro %defcallback (name rettype arg-names arg-types body
                         &key convention)
-  (declare (ignorable convention))
-  (if convention
-      `(clasp-ffi:%defcallback (,name :convention ,convention) ,rettype ,arg-names ,arg-types ,body)
-      `(clasp-ffi:%defcallback ,name ,rettype ,arg-names ,arg-types ,body)
-      ))
+  `(clasp-ffi:%defcallback (,name ,@(when convetion `(:convention ,convention)))
+                           ,rettype ,arg-names ,arg-types ,body))
 
 (defun %callback (name)
   (clasp-ffi:%get-callback name))
```

**Comment by luismbo** [comment]
Also, can you update the manual's _Implementation Support_ chapter?

**Comment by dg1sbg** [comment]
All suggested changes fine for me! Thanks! (and again, I learned some bits of Lisp ;-)

**Comment by dg1sbg** [comment]
Hope the mods in the manual are ok. Please review. Thank you.

**Comment by luismbo** [comment]
Pushed with minor tweaks. Thanks!

**Pull request closed without merging**
