### PR TITLE
try to translate constant enum keywords at compile time

### PR DESCRIPTION
**Pull request by 3b**

### CODE REVIEW

**Comment by luismbo** [comment]
It'd be nice to use a constantp-aware once-only, but not a big deal. CI seems to be MIA. Did you run the test suite?

**Comment by sionescu** [comment]
@luismbo our free Travis credits have run out and we should probably migrate to Github actions.

**Comment by 3b** [comment]
hadn't run tests, was hoping CI would take care of it so I don't have to deal with windows/msys oddness.

Trying now says

```
Unhandled memory fault at #x500000020.
   [Condition of type CFFI-GROVEL:GROVEL-ERROR]
```
from trying to build libffi (and possibly also from running pkg-conf, libffi is installed and pkg-conf seems to be working).

Will try to debug that and/or run tests elsewhere later.

**Comment by luismbo** [comment]
Feel free to skip the libffi tests.

**Comment by 3b** [comment]
It looked more like a problem with `run-program` than libffi specifically, but will try that when i get back to the computer.

**Comment by 3b** [comment]
Yeah, something is wrong with my local setup, i get segfaults from run-program half the time. When tests do run, i get 12 unexpected failures with or without the changes, some look like the run-program problem, some from sprintf failing (`%0.f` always prints "f" or "0"), and a few other random things.

**Comment by 3b** [comment]
on x8664 linux sbcl i get
```
3 out of 342 total tests failed: FSBV.WFO, FSBV.MAKEPAIR.1, FSBV.MAKEPAIR.2.
No unexpected failures.
```
with this branch

**Pull request merged**
