### PR TITLE
Travis: test only master branch

### PR DESCRIPTION
**Pull request by sionescu**
This was a feature branch doesn't get tested twice in a row: once as branch, once as pull request.

### CODE REVIEW

**Comment by luismbo** [comment]
Hmm, why do you push these branches to cffi/cffi instead of sionescu/cffi. I think the latter would be more idiomatic in the GitHub workflow?

**Comment by sionescu** [comment]
More idiomatic when there's only one person with commit access to the main repository. With multiple committers it makes more sense for them to create feature branches and to test only pull requests and the integration branches(master/develop).

**Comment by luismbo** [comment]
Hmm, OK. :) Go ahead and push / cherry-pick this onto master. :+1:

**Comment by sionescu** [comment]
Done

**Pull request closed without merging**
