### PR TITLE
Robustify static linking command printing

### PR DESCRIPTION
**Pull request by fare**
Make the static linking command more robust.

### CODE REVIEW

**Comment by luismbo** [comment]
Care to elaborate on what exactly has been robustified? :-)

**Comment by attila-lendvai** [comment]
but why? isn't he's the sole user? :)

**Comment by fare** [comment]
I updated the commit with additional comments and reformatting and a better commit message.

It is right that I am maybe the only user at this point `:-(`

The original edit was actually done from quite a few weeks ago. I believe I reconstituted the motivation for it in the commit message. Anyway, I was flushing this change from my local repository after a friend asked me a question about cffi-grovel and I wanted to get my code in synch with his.

**Comment by luismbo** [comment]
We need Google Analytics embedded into ASDF or something to track the number of users!

Anyhoo, thanks @fare.

**Pull request merged**
